### PR TITLE
Update fh-mbaas-api to version 8.0.3

### PR DESCRIPTION
**Pull request by davidffrench**

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@davidffrench just a quick one. The ~ actually takes care of bumping the patch version. When the `npm install` is run here it will pick up the most recent patch. I've seen a case before where a bug got in because it was published to npm and it got picked up even though the version was specified as you've done here. Just an fyi.

**Comment by davidffrench** [comment]
@laurafitzgerald thank you, that is a good point.

**Comment by laurafitzgerald** [comment]
@davidffrench nps. Not sure what you want to do with the point. I think probably the ~ should be removed so we can lock the version of fh-mbaas-api for each release. but I am not an active participant currently in feedhenry-templates stuff so only a suggestion.

**Comment by davidffrench** [comment]
@laurafitzgerald unfortunately i don't have the opportunity to change it at this point but it is a good point for the future.

**Pull request merged**
